# Use the official Tomcat image from the Docker Hub
FROM tomcat:8.5-jdk8

LABEL maintainer="hoangclw@gmail.com"

WORKDIR /usr/local/tomcat/webapps/
                  
# Copy the war file to the webapps directory of Tomcat
# ADD ./target/your_lovely_website.war /usr/local/tomcat/webapps/

# Expose port
EXPOSE 8080

# Start Tomcat server
CMD ["catalina.sh", "run"]

# Build command: docker build -t lcaohoanq/tomcat:8.5 -f Dockerfile-tomcat-8.5-jdk8 .
