FROM mysql

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

COPY ./data_student.sql /docker-entrypoint-initdb.d/

# docker built -f Dockerfile.secret -t mysql-secret .
# docker container run --env-file .env 23839752d74d
# docker exec -it <container_id> /bin/bash
# mysql -u root -p
# mysql -u lcaohoanq -p