FROM nginx

WORKDIR /usr/share/nginx/html

# Because already have command WORKDIR, so don't need to specify the path in COPY command, just need from source to destination
COPY index.html index.html
# If have more file to copy, just add more COPY command