services:
  mongodb:
    image: mongo:latest
    container_name: lcaohoanq_mongodb  # Custom container name
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: lcaohoanq_mongodb  # Referencing the named MongoDB container
    ports:
      - "8081:8081"

volumes:
  mongodb_data:
