networks:
  mysql_connector:
    driver: bridge

services:
  mysql:
    image: lcaohoanq/sample-mysql-db:2.0
    container_name: mysql_db
    networks:
      - mysql_connector
    environment:
      MYSQL_ROOT_PASSWORD: Luucaohoang1604^^
      MYSQL_DATABASE: mysql_starter
      MYSQL_USER: lcaohoanq
      MYSQL_PASSWORD: Luucaohoang1604^^
    volumes: 
      - mysql_data:/var/lib/mysql        # Persist MySQL data
    ports:
      - "3303:3306"

  phpmyadmin:
    image: phpmyadmin:5
    container_name: phpmyadmin_ui
    networks:
      - mysql_connector
    environment:
      PMA_HOST: mysql_db                 # Hostname of the MySQL service (container name)
      PMA_USER: root                     # MySQL root user
      PMA_PASSWORD: Luucaohoang1604^^    # MySQL root password
    ports:
      - "81:80"                        # Expose phpMyAdmin on port 81

volumes:
  mysql_data:
    driver: local
